Update commit message in upgrade-python-requirements workflow
edx/.github pull request #4
Opened 2021-03-25 13:33 UTC by Jawayria

Updated the commit message generated on PR by upgrade-python-requirements workflow, to follow conventional commit standards.

JIRA: https://openedx.atlassian.net/browse/BOM-2462

2021-03-25 14:00 UTC, awais786 approved these changes

2021-03-25 14:02 UTC, UsamaSadiq approved these changes

2021-03-25 14:18 UTC, mzulqarnain1 requested changes
I think we should also add `chore:` in PR title.

2021-03-30 09:29 UTC, mzulqarnain1 approved these changes

2021-04-01 08:27 UTC, merged